-- PART 5: TIS HAZARI & DWARKA JURISDICTIONS
-- ==========================================

-- 1. INSERT DISTRICT WEST (Tis Hazari Courts)
INSERT INTO police_stations (station_name, district, address, jurisdictional_court, court_address) VALUES
('Anand Parbat', 'West', 'West District, Delhi', 'Tis Hazari District Courts', 'Tis Hazari, Delhi 110054'),
('Hari Nagar', 'West', 'West District, Delhi', 'Tis Hazari District Courts', 'Tis Hazari, Delhi 110054'),
('Janak Puri Metro', 'West', 'West District, Delhi', 'Tis Hazari District Courts', 'Tis Hazari, Delhi 110054'),
('Khayala', 'West', 'West District, Delhi', 'Tis Hazari District Courts', 'Tis Hazari, Delhi 110054'),
('Kirti Nagar', 'West', 'West District, Delhi', 'Tis Hazari District Courts', 'Tis Hazari, Delhi 110054'),
('Maya Puri', 'West', 'West District, Delhi', 'Tis Hazari District Courts', 'Tis Hazari, Delhi 110054'),
('Mianwali Nagar', 'West', 'West District, Delhi', 'Tis Hazari District Courts', 'Tis Hazari, Delhi 110054'),
('Moti Nagar', 'West', 'West District, Delhi', 'Tis Hazari District Courts', 'Tis Hazari, Delhi 110054'),
('Mundka', 'West', 'West District, Delhi', 'Tis Hazari District Courts', 'Tis Hazari, Delhi 110054'),
('Nangloi', 'West', 'West District, Delhi', 'Tis Hazari District Courts', 'Tis Hazari, Delhi 110054'),
('Nihal Vihar', 'West', 'West District, Delhi', 'Tis Hazari District Courts', 'Tis Hazari, Delhi 110054'),
('Paschim Vihar', 'West', 'West District, Delhi', 'Tis Hazari District Courts', 'Tis Hazari, Delhi 110054'),
('Patel Nagar', 'West', 'West District, Delhi', 'Tis Hazari District Courts', 'Tis Hazari, Delhi 110054'),
('Punjabi Bagh', 'West', 'West District, Delhi', 'Tis Hazari District Courts', 'Tis Hazari, Delhi 110054'),
('Raja Garden Metro', 'West', 'West District, Delhi', 'Tis Hazari District Courts', 'Tis Hazari, Delhi 110054'),
('Rajouri Garden', 'West', 'West District, Delhi', 'Tis Hazari District Courts', 'Tis Hazari, Delhi 110054'),
('Ranhola', 'West', 'West District, Delhi', 'Tis Hazari District Courts', 'Tis Hazari, Delhi 110054');

-- 2. INSERT DISTRICT CENTRAL (Tis Hazari Courts)
INSERT INTO police_stations (station_name, district, address, jurisdictional_court, court_address) VALUES
('Bara Hindu Rao', 'Central', 'Central District, Delhi', 'Tis Hazari District Courts', 'Tis Hazari, Delhi 110054'),
('Burari', 'Central', 'Central District, Delhi', 'Tis Hazari District Courts', 'Tis Hazari, Delhi 110054'),
('Chandni Mahal', 'Central', 'Central District, Delhi', 'Tis Hazari District Courts', 'Tis Hazari, Delhi 110054'),
('Civil Lines', 'Central', 'Central District, Delhi', 'Tis Hazari District Courts', 'Tis Hazari, Delhi 110054'),
('Companies Act', 'Central', 'Special Registry, Delhi', 'Tis Hazari District Courts', 'Tis Hazari, Delhi 110054'),
('Darya Ganj', 'Central', 'Central District, Delhi', 'Tis Hazari District Courts', 'Tis Hazari, Delhi 110054'),
('DBG Road', 'Central', 'Central District, Delhi', 'Tis Hazari District Courts', 'Tis Hazari, Delhi 110054'),
('Delhi Cantt. Railway', 'Central', 'Central District, Delhi', 'Tis Hazari District Courts', 'Tis Hazari, Delhi 110054'),
('Gulabi Bagh', 'Central', 'Central District, Delhi', 'Tis Hazari District Courts', 'Tis Hazari, Delhi 110054'),
('Hauz Qazi', 'Central', 'Central District, Delhi', 'Tis Hazari District Courts', 'Tis Hazari, Delhi 110054'),
('Hazrat Nizamuddin Railway', 'Central', 'Central District, Delhi', 'Tis Hazari District Courts', 'Tis Hazari, Delhi 110054'),
('I.P. Estate', 'Central', 'Central District, Delhi', 'Tis Hazari District Courts', 'Tis Hazari, Delhi 110054'),
('Income Tax Act', 'Central', 'Special Registry, Delhi', 'Tis Hazari District Courts', 'Tis Hazari, Delhi 110054'),
('Jama Masjid', 'Central', 'Central District, Delhi', 'Tis Hazari District Courts', 'Tis Hazari, Delhi 110054'),
('Kamla Market', 'Central', 'Central District, Delhi', 'Tis Hazari District Courts', 'Tis Hazari, Delhi 110054'),
('Karol Bagh', 'Central', 'Central District, Delhi', 'Tis Hazari District Courts', 'Tis Hazari, Delhi 110054'),
('Kashmere Gate Metro', 'Central', 'Central District, Delhi', 'Tis Hazari District Courts', 'Tis Hazari, Delhi 110054'),
('Kashmere Gate', 'Central', 'Central District, Delhi', 'Tis Hazari District Courts', 'Tis Hazari, Delhi 110054'),
('Kotwali', 'Central', 'Central District, Delhi', 'Tis Hazari District Courts', 'Tis Hazari, Delhi 110054'),
('Lahori Gate', 'Central', 'Central District, Delhi', 'Tis Hazari District Courts', 'Tis Hazari, Delhi 110054'),
('Maurice Nagar', 'Central', 'Central District, Delhi', 'Tis Hazari District Courts', 'Tis Hazari, Delhi 110054'),
('Nabi Karim', 'Central', 'Central District, Delhi', 'Tis Hazari District Courts', 'Tis Hazari, Delhi 110054'),
('New Delhi Railway Station (NDLS)', 'Central', 'Central District, Delhi', 'Tis Hazari District Courts', 'Tis Hazari, Delhi 110054'),
('Old Delhi Railway Station (Railway Main Delhi)', 'Central', 'Central District, Delhi', 'Tis Hazari District Courts', 'Tis Hazari, Delhi 110054'),
('Pahar Ganj', 'Central', 'Central District, Delhi', 'Tis Hazari District Courts', 'Tis Hazari, Delhi 110054'),
('Prasad Nagar', 'Central', 'Central District, Delhi', 'Tis Hazari District Courts', 'Tis Hazari, Delhi 110054'),
('Railway Protection Force (RPF)', 'Central', 'Special Agency, Delhi', 'Tis Hazari District Courts', 'Tis Hazari, Delhi 110054'),
('Rajinder Nagar', 'Central', 'Central District, Delhi', 'Tis Hazari District Courts', 'Tis Hazari, Delhi 110054'),
('Roop Nagar', 'Central', 'Central District, Delhi', 'Tis Hazari District Courts', 'Tis Hazari, Delhi 110054'),
('Sadar Bazar', 'Central', 'Central District, Delhi', 'Tis Hazari District Courts', 'Tis Hazari, Delhi 110054'),
('Sarai Rohilla', 'Central', 'Central District, Delhi', 'Tis Hazari District Courts', 'Tis Hazari, Delhi 110054'),
('Sarai Rohilla Railway', 'Central', 'Central District, Delhi', 'Tis Hazari District Courts', 'Tis Hazari, Delhi 110054'),
('Seed Act', 'Central', 'Special Registry, Delhi', 'Tis Hazari District Courts', 'Tis Hazari, Delhi 110054'),
('Subzi Mandi', 'Central', 'Central District, Delhi', 'Tis Hazari District Courts', 'Tis Hazari, Delhi 110054'),
('Subzi Mandi Railway', 'Central', 'Central District, Delhi', 'Tis Hazari District Courts', 'Tis Hazari, Delhi 110054'),
('Prevention of Cruelty of Animals Act 1960 (SPCA)', 'Central', 'Special Registry, Delhi', 'Tis Hazari District Courts', 'Tis Hazari, Delhi 110054'),
('Timarpur', 'Central', 'Central District, Delhi', 'Tis Hazari District Courts', 'Tis Hazari, Delhi 110054'),
('Wildlife Protection Act 1972', 'Central', 'Special Registry, Delhi', 'Tis Hazari District Courts', 'Tis Hazari, Delhi 110054');

-- 3. INSERT DISTRICT SOUTH-WEST (Dwarka Courts)
INSERT INTO police_stations (station_name, district, address, jurisdictional_court, court_address) VALUES
('Baba Haridas Nagar', 'South-West', 'South-West District, Delhi', 'Dwarka District Courts', 'Sector 10, Dwarka, New Delhi 110075'),
('Binda Pur', 'South-West', 'South-West District, Delhi', 'Dwarka District Courts', 'Sector 10, Dwarka, New Delhi 110075'),
('Chhawla', 'South-West', 'South-West District, Delhi', 'Dwarka District Courts', 'Sector 10, Dwarka, New Delhi 110075'),
('Dabri', 'South-West', 'South-West District, Delhi', 'Dwarka District Courts', 'Sector 10, Dwarka, New Delhi 110075'),
('Delhi Cantonment Board', 'South-West', 'Special Registry, Delhi', 'Dwarka District Courts', 'Sector 10, Dwarka, New Delhi 110075'),
('Dwarka North', 'South-West', 'South-West District, Delhi', 'Dwarka District Courts', 'Sector 10, Dwarka, New Delhi 110075'),
('Dwarka Sector-23', 'South-West', 'South-West District, Delhi', 'Dwarka District Courts', 'Sector 10, Dwarka, New Delhi 110075'),
('Dwarka South', 'South-West', 'South-West District, Delhi', 'Dwarka District Courts', 'Sector 10, Dwarka, New Delhi 110075'),
('Jaffarpur Kalan', 'South-West', 'South-West District, Delhi', 'Dwarka District Courts', 'Sector 10, Dwarka, New Delhi 110075'),
('Janak Puri', 'South-West', 'South-West District, Delhi', 'Dwarka District Courts', 'Sector 10, Dwarka, New Delhi 110075'),
('Kapashera', 'South-West', 'South-West District, Delhi', 'Dwarka District Courts', 'Sector 10, Dwarka, New Delhi 110075'),
('Najafgarh', 'South-West', 'South-West District, Delhi', 'Dwarka District Courts', 'Sector 10, Dwarka, New Delhi 110075'),
('Palam Domestic Airport', 'South-West', 'South-West District, Delhi', 'Dwarka District Courts', 'Sector 10, Dwarka, New Delhi 110075'),
('Palam Village', 'South-West', 'South-West District, Delhi', 'Dwarka District Courts', 'Sector 10, Dwarka, New Delhi 110075'),
('Uttam Nagar', 'South-West', 'South-West District, Delhi', 'Dwarka District Courts', 'Sector 10, Dwarka, New Delhi 110075'),
('Vikas Puri', 'South-West', 'South-West District, Delhi', 'Dwarka District Courts', 'Sector 10, Dwarka, New Delhi 110075');
